- name: Install patches and reboot server
  hosts: test_servers
  become: yes
  tasks:
    - name: Install security updates
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - "openssl"
        - "curl"

    - name: Reboot the machine if necessary
      reboot:
        reboot_timeout: 600
        test_command: uptime
        msg: "Rebooting the machine after patching"
    
    - name: Get uptime after reboot
      shell: uptime  # Run uptime command
      register: uptime_output

    - name: Show the output of the test_command (uptime) immediately
      debug:
        msg: "Reboot test command output: {{ uptime_output.stdout }}"
      when: uptime_output is defined  # Only run if reboot_result was registered
